--- 
app_names:
  audio_features_processor: AudioFeaturesProcessorProd
debug: false
kinesis:
  endpoints:
    audio_features: https://kinesis.us-east-1.amazonaws.com
    audio_products: https://kinesis.us-east-1.amazonaws.com
  streams:
    audio_features: audio_features
    audio_products: audio_products

graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - com.hello

logging: 
  level: ERROR
  loggers: 
    com.hello.jeipoppu: ERROR

max_records: 50

metrics_enabled: false